@startuml
skinparam componentStyle rectangle
actor 学生 
actor 教員 
[利用者] --o 学生
[利用者] --o 教員
学生 --o [学生証]
教員 --o [職員証]
[学生証] --o [貸出履歴]
[職員証] --o [貸出履歴]
[学生証] <-- [学籍番号]
[職員証] <-- [職員番号]
[書籍] o-- [貸出履歴]
[書籍] <-- [タイトル]
[書籍] <-- [管理番号]
[貸出履歴] --o [貸出日]
[貸出日] --o [返却日]
[貸出履歴] --o [貸出冊数]
[貸出履歴] --o [予約の有無]
[学生名] --> [学生証]
[教員名] --> [職員証]

@enduml