@startuml 修正案
skinparam componentStyle rectangle

[図書] -- [管理番号]
[図書] -- [雑誌]
[図書] -- [書籍]

[利用者] -- [学籍番号]
[利用者] -- [職員番号]
[利用者] -- [会員番号]
[貸出履歴] -- [予約状態]

[利用者] -- [会員番号]
[貸出履歴] -- [貸出日]
[貸出履歴] -- [返却日]
[図書] -- [貸出履歴]
[利用者] -- [学生]
[利用者] -- [職員]
[学生] -- [学生証]
[職員] -- [職員証]
[利用者] -- [メールアドレス]

@enduml