@startuml 訪問者システム
skinparam classAttributeIconSize 0
class RoboDog {
    '属性
    -Webページ
    -訪問者
    -ユーザID
    -パスワード
    -名前
    -学校名
    -所属名
    -メールアドレス
    -電話番号
    -年齢
    -登録情報


    '操作
    +登録情報を登録できる()
    +登録情報を参照できる()
    +登録情報を変更できる()
    +登録情報を削除できる()
    
}

@enduml