@startuml 訪問者システム_クラス図

skinparam classAttributeIconSize 0
class 訪問者システム {
    '属性
    -Webページ
    -訪問者
    -登録情報
    -ユーザID
    -パスワード
    -名前
    -学校名
    -所属名
    -メールアドレス
    -電話番号
    -年齢

    '操作
    +登録情報を登録する()
    +自他で登録情報を参照する()
    +登録情報を変更する()
    +登録情報を削除する()
    +ログインする()
    +ログアウトする()
    
}

@enduml