@startuml 訪問者登録情報を参照できる（参照）
left to right direction
actor 訪問者 as U1

rectangle 登録情報 as WRS {
  usecase 名前 as UC1
  usecase 学校名 as UC2
  usecase 所属名 as UC3
  usecase メールアドレス as UC4
  usecase 電話番号 as UC5
  usecase 年齢 as UC6
}


U1 --> UC1
U1 --> UC2
U1 --> UC3
U1 --> UC4
U1 --> UC5
U1 --> UC6
@enduml