@startuml Robodogドメインモデル図
skinparam componentStyle rectangle

' 
[会社] --[Web販売システム]
[会社] -- [注文管理システム]
[注文管理システム] -- [Web販売システム]
[注文管理システム] -- [注文]
[Web販売システム] -- [注文]
[管理者] -- [注文管理システム]
[顧客] -- [Web販売システム]
[顧客] -- [顧客ID]
[顧客] -- [氏名]
[顧客] -- [住所]
[顧客] -- [電話番号]
[顧客] -- [メールアドレス]
[注文] -- [注文ID]
[注文] -- [注文日]
[注文] -- [合計金額]
[商品] -- [商品ID]
[商品] -- [商品名]
[商品] -- [価格]
[商品] -- [在庫数量]
[注文] -- [顧客]
[注文] -- [商品]
[注文] -- [数量]

[管理者] -- [管理者ID]
[管理者] -- [パスワード]


@enduml