@startuml Robodog統合ドメインモデル図
skinparam componentStyle rectangle

' =====================
' 顧客
' =====================
[顧客] o-- [顧客ID]
[顧客] o-- [氏名]
[顧客] o-- [住所]
[顧客] o-- [電話番号]
[顧客] o-- [メールアドレス]
[顧客] o-- [顧客パスワード]
[顧客] o-- [クレジットカード情報]

' =====================
' 商品
' =====================
[商品] o-- [商品ID]
[商品] o-- [商品名]
[商品] o-- [本体価格]
[商品] o-- [在庫数量]

' =====================
' 注文
' =====================
[注文] o-- [注文ID]
[注文] o-- [注文日]
[注文] o-- [数量]
[注文] o-- [合計金額]

[顧客] -- [注文]
[商品] -- [注文]

' =====================
' 注文状況
' =====================
[注文] -- [注文状況]

[注文状況] <|-- [注文申請]
[注文状況] <|-- [出荷準備中]
[注文状況] <|-- [出荷中]
[注文状況] <|-- [出荷完了]
[注文状況] <|-- [注文キャンセル]
[注文状況] <|-- [商品回収中]
[注文状況] <|-- [商品回収済み]
[注文状況] <|-- [返金処理中]
[注文状況] <|-- [返金処理完了]

' =====================
' 支払い情報（クレカ専用）
' =====================
[支払い情報] o-- [支払いID]
[支払い情報] o-- [カードトークンID]
[支払い情報] o-- [決済状況]

[注文] -- [支払い情報]

' =====================
' 管理システム利用者
' =====================
[管理システム利用者] o-- [ID]
[管理システム利用者] o-- [パスワード]
[管理システム利用者] <|-- [倉庫業者]
[管理システム利用者] <|-- [カスタマーサポーター]
[管理システム利用者] <|-- [アカウント管理者]

@enduml
