@startuml Robodogドメインモデル図
skinparam componentStyle rectangle

[顧客] o-- [顧客ID]
[顧客] o-- [氏名]
[顧客] o-- [住所]
[顧客] o-- [電話番号]
[顧客] o-- [メールアドレス]
[顧客] o-- [顧客パスワード]

[注文] o-- [注文ID]
[注文] o-- [注文日]
[注文] o-- [合計金額]
[注文] o-- [数量]
[注文] o-- [注文状況]

[商品] o-- [商品ID]
[商品] o-- [商品名]
[商品] o-- [価格]
[商品] o-- [在庫数量]

[商品] -- [顧客]
[注文] -- [商品]
[顧客] -- [注文]

[管理者] o-- [管理者ID]
[管理者] o-- [管理者パスワード]


@enduml