@startuml Robodogドメインモデル図
skinparam componentStyle rectangle

[注文管理システム] -- [Web販売システム]
[注文管理システム] -- [注文番号]
[Web販売システム] -- [注文番号]
[管理者] -- [注文管理システム]
[顧客情報] -- [Web販売システム]
[顧客情報] -- [顧客ID]
[顧客情報] -- [氏名]
[顧客情報] -- [住所]
[顧客情報] -- [電話番号]
[顧客情報] -- [メールアドレス]
[顧客情報] -- [顧客パスワード]
[注文番号] -- [注文ID]
[注文番号] -- [注文日]
[注文番号] -- [合計金額]
[商品] -- [商品ID]
[商品] -- [商品名]
[商品] -- [価格]
[商品] -- [在庫数量]
[注文番号] -- [顧客情報]
[注文番号] -- [商品]
[注文番号] -- [数量]

[管理者] -- [管理者ID]
[管理者] -- [管理者パスワード]


@enduml