@startuml
skinparam classAttributeIconSize 0

class 注文管理システム
class Web販売システム
class 顧客情報 {
  顧客ID
  氏名
  住所
  電話番号
  メールアドレス
  顧客パスワード
}
class 注文 {
  注文ID
  注文日
  合計金額
  数量
}
class 商品 {
  商品ID
  商品名
  価格
  在庫数量
}
class 管理者 {
  管理者ID
  管理者パスワード
}

注文管理システム -- Web販売システム
注文管理システム -- 注文
Web販売システム -- 注文
Web販売システム -- 顧客情報
注文 -- 顧客情報
注文 -- 商品
注文 -- 注文管理システム
管理者 -- 注文管理システム

@enduml