@startuml BBショップシステム_クラス図

skinparam classAttributeIconSize 0
class システム管理者 {
    '属性
    -管理者ID
    -管理者パスワード
    -注文ID
    -注文日
    -数量
    -商品ID
    -商品名

    '操作
    +ログインする()
    +ログアウトする()
    +注文履歴を確認する()
    +在庫を確認する()
}

skinparam classAttributeIconSize 0
class 倉庫業者 {
    '属性
    -管理者ID
    -管理者パスワード
    -注文ID
    -数量
    -商品ID
    -商品名

    '操作
    +ログインする()
    +ログアウトする()
    +在庫を確認する()
}

skinparam classAttributeIconSize 0
class カスタムマーサポーター {
    '属性
    -管理者ID
    -管理者パスワード
    -顧客ID
    -氏名
    -メールアドレス
    -クレジットカード情報

    '操作
    +ログインする()
    +ログアウトする()
    +クレジットカード会社に返金処理を依頼する()
}

@enduml