@startuml BBショップシステム_クラス図
skinparam classAttribute 0
class 管理者 {
    -権能ID
    -社員ID
    -管理者パスワード
    +ログインする()
    +ログアウトする()
}


skinparam classAttributeIconSize 0
class アカウント管理者 {
    '属性
    -顧客情報

    '操作
    +アカウントを変更する()
    +アカウントを停止する()
}

skinparam classAttributeIconSize 0
class 倉庫業者 {
    '属性
    -注文履歴
    -在庫情報

    '操作
    +在庫を確認する()
    +注文履歴を確認する()
}

skinparam classAttributeIconSize 0
class カスタムマーサポーター {
    '属性
    -顧客情報
    -注文履歴
    -メールアドレス
    -クレジットカード情報

    '操作
    +クレジットカード会社に返金処理を依頼する()
    +注文履歴を確認する()
    +お問い合わせに対応する()
}

skinparam classAttributeIconSize 0
class 顧客 {
    '属性
    -顧客ID
    -顧客パスワード
    -氏名
    -住所
    -電話番号
    -メールアドレス

    '操作
    +ログインする()
    +ログアウトする()
    +会員登録する()
    +会員情報を変更する()
    +商品を注文する()
    +クレジットカード情報を入力する()
    +注文履歴を確認する()
    +商品を検索する()
    +お問い合わせする()
    +注文をキャンセルする()
    +商品を閲覧する()
    +新規登録する()
}

skinparam classAttributeIconSize 0
class 商品 {
    '属性
    -商品ID
    -商品名
    -本体価格
    -在庫数量

    '操作
    +数量を表示する()
    +商品情報と本体価格を表示する()
}

skinparam classAttributeIconSize 0
class 注文 {
    '属性
    -注文ID
    -注文日
    -税込金額
    -数量
    -注文状況

    '操作
    +注文日を記録する()
    +注文状況を更新する()
}

' 関連性の定義
' **汎化（継承）**には多重度は使用しません
管理者 <|-- アカウント管理者
管理者 <|-- 倉庫業者
管理者 <|-- カスタムマーサポーター

' **関連**と**集約**に多重度 0..* を適用

' 1. 顧客と注文
' 顧客は0件以上の注文をする。注文は必ず1人の顧客に紐づく（必須）ため、**1**と**0..***の組み合わせとします。
顧客 "1" -- "0..*" 注文 : 注文する >

' 2. 注文と商品（集約）
' 注文は1種類以上の商品を含み（**1..***）、商品は0件以上の注文に含まれる可能性があります（**0..***）。
注文 "1..*" o-- "0..*" 商品 : 含む
' 3. 注文とクレジットカード情報（集約）
' 注文は0件以上のクレジットカード情報を含み（** 0..***）、クレジットカード情報は0件以上の注文に含まれる可能性があります（**0..***）。
注文 "0..*" o-- "0..*" カード情報 : 含む

' 4. 顧客と商品
' 顧客は0件以上の商品を閲覧・検索し、商品は0人以上の顧客に閲覧される。
顧客 "0..*" --> "0..*" 商品 : 閲覧・検索

@enduml