@startuml BBショップシステム_クラス図

skinparam classAttributeIconSize 0
class システム管理者 {
    '属性
    -管理者ID
    -管理者パスワード
    -注文ID
    -注文日
    -数量
    -商品ID
    -商品名

    '操作
    +ログインする()
    +ログアウトする()
    +注文履歴を確認する()
    +在庫を確認する()
}

skinparam classAttributeIconSize 0
class 倉庫業者 {
    '属性
    -管理者ID
    -管理者パスワード
    -注文ID
    -数量
    -商品ID
    -商品名

    '操作
    +ログインする()
    +ログアウトする()
    +在庫を確認する()
}

skinparam classAttributeIconSize 0
class カスタムマーサポーター {
    '属性
    -管理者ID
    -管理者パスワード
    -顧客ID
    -氏名
    -メールアドレス
    -クレジットカード情報

    '操作
    +ログインする()
    +ログアウトする()
    +クレジットカード会社に返金処理を依頼する()
}

skinparam classAttributeIconSize 0
class 顧客 {
    '属性
    -顧客ID
    -顧客パスワード
    -氏名
    -住所
    -電話番号
    -メールアドレス
    -クレジットカード情報

    '操作
    +ログインする()
    +ログアウトする()
    +会員登録する()
    +会員情報を変更する()
    +商品を注文する()
    +クレジットカード情報を入力する()
    +注文履歴を確認する()
    +商品を検索する()
}

skinparam classAttributeIconSize 0
class 商品 {
    '属性
    -商品ID
    -商品名
    -本体価格
    -在庫数量

    '操作
    +数量を表示する()
    +商品情報と本体価格を表示する()
    +在庫を確認する()
    +商品を注文する()
}

skinparam classAttributeIconSize 0
class 注文 {
    '属性
    -注文ID
    -注文日
    -税込金額
    -数量
    -注文状況

    '操作
    +注文日を記録する()
    +注文状況を共有する()
}

@enduml