@startuml BBショップシステム_クラス図

skinparam classAttributeIconSize 0
class 顧客 {
    '属性
    -商品ID
    -商品名
    -定価価格
    -税込み価格
    -顧客ID
    -顧客のパスワード
    -氏名
    -住所
    -電話番号
    -メールアドレス
    -クレジットカード情報

    '操作
    +ログインする()
    +ログアウトする()
    +商品を注文する()
    +注文をキャンセルする()
    +返品する()
}

skinparam classAttributeIconSize 0
class 管理者 {
    '属性
    -管理者ID
    -管理者パスワード
    -顧客ID
    -氏名
    -住所
    -メールアドレス
    -クレジットカード情報
    -注文ID
    -注文日
    -数量
    -商品ID
    -商品名

    '操作
    +ログインする()
    +ログアウトする()
    +注文履歴を確認する()
    +クレジットカード会社に返金処理を依頼する()
    +在庫を確認する()
    +商品を回収する()
}

@enduml