@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho

' ==== 抽象クラス ====
abstract class 利用者 {
  - 会員番号
  - 氏名
  - メールアドレス
  - 上限冊数
  + 貸出(図書)
  + 返却(図書)
  + 予約(図書)
}

' ==== 派生クラス ====
class 学生 {
  - 学生番号
  {static} 上限冊数 = 6
}

class 教職員 {
  - 職員番号
  {static} 上限冊数 = 12
}

利用者 <|-- 学生
利用者 <|-- 教職員

' ==== 図書系 ====
abstract class 図書 {
  - 管理番号
  - タイトル
  - 貸出可能
  - ISBN
  + 貸出可否確認()
}

class 書籍 
class 雑誌 

図書 <|-- 書籍
図書 <|-- 雑誌

' ==== 貸出・予約・通知 ====
class 貸出履歴 {
  - 貸出日
  - 返却日
}

class 予約情報{
  - 予約日
}



' ==== 関係 ====
利用者 "1" -- "0..*" 貸出履歴 : 貸出記録
図書 "1" -- "0..*" 貸出履歴 : 対応
利用者 "1" -- "0..*" 予約情報
図書 "1" -- "0..*" 予約情報
@enduml