@startuml 名前変更
left to right direction
actor "ユーザー" as fc
rectangle RoboDog {
  usecase "名前の変更" as UC1
  usecase "新しい名前を入力して変更ボタンを押す" as UC2
  usecase "名前の変更結果を表示する" as UC3
}
fc -- UC1
fc -- UC2
fc -- UC3
@enduml
