@startuml Reservation
actor 事務職員
boundary 図書予約画面
control 会員確認
entity 会員情報
control 画面表示制御
control 図書確認
entity 図書情報
control 図書一覧
control 予約保存
entity 予約情報
boundary 予約完了画面

事務職員 -> 図書予約画面 : 予約メニューを押す
図書予約画面 -> 会員確認 : 会員番号を入力
会員確認 -> 会員情報 : 確認
会員情報 --> 会員確認 : 確認結果返却

alt 未登録 or 未入力
    会員確認 -> 図書予約画面 : 「会員番号を確認してください」と表示
else 登録済み
    会員確認 -> 画面表示制御 : 会員の氏名・会員種別を表示
    画面表示制御 -> 図書確認 : 書名を入力
    図書確認 -> 図書情報 : 確認
    図書情報 --> 図書確認 : 図書情報返却


    alt 書名未入力
        図書確認 -> 画面表示制御 : 「書名を入力してください」と表示
    else 該当なし
        図書確認 -> 画面表示制御 : 「該当する図書が見つかりません」と表示
    else 該当あり
        図書確認 -> 図書一覧 : 図書一覧を表示
        alt 在庫あり
            予約保存 -> 画面表示制御 : 「在庫があります」と表示
            図書一覧 -> 予約保存 : 図書の予約を保存
            予約保存 -> 予約情報 : 保存処理
            予約情報 --> 予約保存 : 保存結果
            予約完了画面 -> 予約保存 : 保存が確認できた
            予約保存 -> 予約完了画面 : 遷移
        else 学生は雑誌を予約
            予約保存 -> 画面表示制御 : 「学生は雑誌を予約できません」と表示
        else 未貸し出しの本がある
            予約保存 -> 画面表示制御 : 「在庫があります」と表示
        end
    end
end
@enduml