@startuml
title 貸出履歴照会のシーケンス図

actor 事務職員
boundary 貸出履歴メニュー画面
control 書名検索
entity 図書情報
control 一致する図書の一覧表示
control 貸出履歴処理
entity 貸出情報
boundary 貸出履歴画面

事務職員 -> 貸出履歴メニュー画面: 貸出履歴メニューを押す

貸出履歴メニュー画面 -> 書名検索: 書名を入力し検索ボタンを押す
貸出履歴メニュー画面 -> 書名検索: 書名検索を要求

書名検索 -> 図書情報: 確認
図書情報 --> 書名検索: 一致結果を返す

alt 書名が未入力
    書名検索 -> 貸出履歴メニュー画面: 「書名を入力してください」と表示
else 該当する図書がない
    書名検索 -> 貸出履歴メニュー画面: 「該当する図書がありません」と表示
else 書名が部分一致
    書名検索 -> 一致する図書の一覧表示: 一致する図書を一覧表示

    事務職員 -> 一致する図書の一覧表示: 履歴を閲覧したい図書の管理番号を押す
    一致する図書の一覧表示 -> 貸出履歴処理: 貸出履歴件数確認
    貸出履歴処理 -> 貸出情報: 貸出履歴件数確認
    貸出情報 --> 貸出履歴処理: 貸出履歴件数を返す

    alt 該当する貸出履歴件数が0
        貸出履歴処理 -> 貸出履歴メニュー画面: 「貸出履歴がありません」と表示
    else
        貸出履歴処理 -> 貸出履歴画面: 貸出履歴画面表示
    end
end

@enduml
