@startuml メニュー項目
left to right direction
actor "事務職員" as ac1
' actor "会員" as ac2
rectangle  大原情報科学大学・図書館システム{
  usecase "「貸し出し予約」の受付" as UC1
  usecase "貸し出し" as UC2
  usecase "返却" as UC3
  usecase "記録" as UC4
  usecase "閲覧" as UC5
  usecase "メール送信" as UC6
}
' ac2 -- UC0
ac1 -- UC1
ac1 -- UC2
ac1 -- UC3
ac1 -- UC4
ac1 -- UC5
ac1 -- UC6
@enduml