@startuml RoboDogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
    -名前
    -1つ目の整数
    -2つ目の整数
    -時刻
    -挨拶
    -足し算結果
    -朝の挨拶
    -昼の挨拶
    -夜の挨拶

    +getMyName()
    +setMyName()
    +setNewTime()
    +getMyGreeting()
    +2つの整数を取得()
    +足し算の登録()
    +足し算結果の取得()

}
@enduml