@startuml
skinparam classAttributeIconSize 0
class RoboDog {
    -名前
    -1つ目の整数
    -2つ目の整数
    -時刻
    -挨拶
    -足し算結果
    -朝の挨拶
    -昼の挨拶
    -夜の挨拶

    +getMyName()
    +setMyName()
    +時刻の設定()
    +時刻に応じた挨拶の取得()
    +2つの整数を取得()
    +足し算の登録()
    +足し算結果の取得()

}
@enduml