@startuml RoboDogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
    -myName: String
    ' datetime? bigInt?=UNIXTIME
    ' UNIXTIMEは1970年1月1日0時0分0秒からの経過秒数
    -myTime: int
    -goodMorning: String
    -goodAfternoon: String
    -goodNight: String
    -firstValue: int
    -secondValue: int
    ' 教科書にはない
    -Result: int

    +getMyName(): String
    +setMyName(): int
    +setNewTime(): void
    +getMyGreeting(): String
    +setFirstValue(): int
    +setSecondValue(): int
    +getAddition(): int
    ' 教科書にはない
    +setValues: int
    +setAddResult(): int

}
@enduml