@startuml 注文管理システム
left to right direction

actor 管理者

rectangle 注文管理システム {

  usecase "ログインする" as Admin_Login
  usecase "ログアウトする" as Admin_Logout
  usecase "注文履歴を確認する" as Admin_CheckHistory
  usecase "クレジットカード会社に返金処理をする" as Admin_Refund
  usecase "在庫を確認する" as Admin_CheckStock


}

管理者 --> Admin_Login
管理者 --> Admin_Logout
管理者 --> Admin_CheckHistory
管理者 --> Admin_Refund
管理者 --> Admin_CheckStock

@enduml
