@startuml Web販売システム
left to right direction

actor 顧客

rectangle Web販売システム {
  
  package "ログイン不要" {
    usecase "商品を閲覧する" as UC_Browse
    usecase "ログインする" as UC_Login
  }

  package "ログイン必須" {
    usecase "商品を注文する" as UC_Order
    usecase "注文をキャンセルする" as UC_Cancel
    usecase "ログアウトする" as UC_Logout
  }
}

顧客 --> UC_Browse
顧客 --> UC_Login
顧客 --> UC_Logout
顧客 --> UC_Order
顧客 --> UC_Cancel

@enduml
