@startuml 注文管理システム
left to right direction

' アクター定義
actor システム管理者
actor 倉庫業者
actor カスタマーサポーター

rectangle 注文管理システム {
  usecase "ログイン" as UC_Login
  usecase "ログアウト" as UC_Logout
  usecase "注文履歴確認" as UC_CheckHistory
  usecase "在庫確認" as UC_CheckStock
  usecase "返金処理（クレジットカード会社）" as UC_Refund
  usecase "アカウント変更" as UC_UpdateAccount
  usecase "アカウント削除" as UC_DeleteAccount
}

' システム管理者のユースケース
システム管理者 --> UC_Login
システム管理者 --> UC_Logout
システム管理者 --> UC_UpdateAccount
システム管理者 --> UC_DeleteAccount

' カスタマーサポーターのユースケース
カスタマーサポーター --> UC_Login
カスタマーサポーター --> UC_Logout
カスタマーサポーター --> UC_CheckHistory
カスタマーサポーター --> UC_Refund

' 配送業者のユースケース
倉庫業者 --> UC_Login
倉庫業者 --> UC_Logout
倉庫業者 --> UC_CheckStock

@enduml